### ISSUE TITLE
Max speed in zone

### ISSUE THREAD

**Issue by ItsNotSpaghetti** [MestroGroup/mgTimer-Public#1]
when bhopping in start zone, max speed is 351 constant and once landing on a ramp it immediately slows you down not allowing to surf. prestrafe does not affect this

**Comment by MestroGroup** [comment]
Appears to be an issue if the data hasn't fully loaded.
Will close for now as this will require further reproduction steps.

**Comment by ItsNotSpaghetti** [comment]
https://drive.google.com/file/d/1CmOpdybHNToCcKPHOwshdsLfafTy7kq4/view?usp=sharing prehop glitch
