### ISSUE TITLE
Spectator key presses 

### ISSUE THREAD

**Issue by cynlik** [MestroGroup/mgTimer-Public#10]
Only ducking shows up 

pressing duck bind show +D on spectator

**Comment by MestroGroup** [comment]
Jumping & Slow does not show.

**Comment by cynlik** [comment]
+duck = +D ----> change to user keybind for duck
+jump no show
+left = +L -----> possibly remove(?)
+right = +R -----> possibly remove(?)

**Comment by MestroGroup** [comment]
Improvements added - Needs further investigation and testing for Jump.

**Comment by MestroGroup** [comment]
Resolved.
