### ISSUE TITLE
BOT: replays stage replay over and over again

### ISSUE THREAD

**Issue by cynlik** [MestroGroup/mgTimer-Public#14]
expected to replay only 1 to full completion

**Comment by MestroGroup** [comment]
Working as intended.
Will play replay 3 times and then move to Stage 2.

**Comment by cynlik** [comment]
instead of stopping replay after looping all stages it keeps replaying the whole map 3 times each stage

intended or not?

**Comment by MestroGroup** [comment]
Not intended.

**Comment by MestroGroup** [comment]
Reproduction steps required to take further action.

**Comment by cynlik** [comment]
reproduction steps:

press E to play then select WRCPs and it will replicate itself

**Comment by MestroGroup** [comment]
Unable to reproduce. Closed.
