### ISSUE TITLE
When a record is set by a player. the stage time is reset after every stage complete if the user has a record

### ISSUE THREAD

**Issue by ItsNotSpaghetti** [MestroGroup/mgTimer-Public#25]
https://drive.google.com/file/d/1iEF2B3uE724KWV73J4z3DEsBrdWorGEc/view?usp=sharing

**Comment by MestroGroup** [comment]
As per last night; we were testing this and unable to reproduce.
It looks as though the timer was displaying the stage timer, as opposed to the usual map timer.

The reason for this remains unknown, further testing required.
