### ISSUE TITLE
!styles arent forced like normally

### ISSUE THREAD

**Issue by ItsNotSpaghetti** [MestroGroup/mgTimer-Public#3]
when doing half side ways sideways etc it doesnt force the user to do it and if going forward it makes you reset your time and puts the style back to normal https://drive.google.com/drive/folders/1D9qzXR6-DL_jaroMnPzu5dXNLmAziKjR?usp=sharing

**Comment by MestroGroup** [comment]
Possibly working as intended as styles are more enforceable using this method.

**Comment by ItsNotSpaghetti** [comment]
No because the timer resets to normal and doesn't allow any non normal time to be set

**Comment by MestroGroup** [comment]
Closed #5 as Duplicate

BHOP HSW = W/A or W/D
SURF HSW = W/A and S/D or W/D and S/A

Expected:

surf server to allow only use of W/A and S/D or W/D and S/A
bhop server to allow only use of W/A or W/D

**Comment by MestroGroup** [comment]
SW and HSW issue resolved.
