### ISSUE TITLE
sm_prac resets timer

### ISSUE THREAD

**Issue by cynlik** [MestroGroup/mgTimer-Public#31]
expected for timer to keep going

suggestion: make it save current time when using sm_cp

**Comment by cynlik** [comment]
community suggestion: make it save current time of sm_cp usage

**Comment by obsidian5m** [comment]
For example:
In the current system, I can set a cp 25% through the map and my timer might display 14:71. If I go past that checkpoint and use sm_tele to go back to the cp, my timer resets to 00:00. 
Ideally, we'd want the sm_tele to reference the same time that the player set the cp at - so I could hit sm_tele, go back to 25% and be at 14:71 again.

This allows players to see what their theoretical best is, as well as maintaining the current ability to practice the map.

**Comment by MestroGroup** [comment]
Should be hotfixed 2607 (Added Suggestion)
