### ISSUE TITLE
sm_pause not working

### ISSUE THREAD

**Issue by cynlik** [MestroGroup/mgTimer-Public#32]
expected to pause timer and freeze movement

maybe add !pause /pause commands for chat use? (don't know if they're already included)

**Comment by obsidian5m** [comment]
This command lets people pause their time on a boost trigger, allowing players to double-boost. In my opinion, this shouldn't exist, OR should only be possible in a start/stage zone.

**Comment by cynlik** [comment]
possible fix would maybe remove all speed from players upon usage?
or only allow usage if user speed is equal to 0 AND is not moving, meaning standing still

**Comment by MestroGroup** [comment]
Hotfix 2507 in preparation for testing session on 2607 - Please feel free to test before the hotfix session specifically to reproduce the above mentiuoned boost by WillSO93.

**Comment by obsidian5m** [comment]
Current sm_pause DOES pause your timer but looks like it doesn't.

When you hit pause, it locks you in place and saves your current time, but the timer in the bottom of your screen keeps running. When you unpause, the time resets to what it was when you paused.

e.g. Surfing, pause at 5 seconds and count to 5. Your timer will still count up to 10 seconds. Unpause and your timer will revert to 5 seconds.

Expect that the timer will stay at 5 seconds (and not keep counting).

Re: double-boosting via this method. Difficult for me to test as I don't have showtriggers - but I was able to reproduce the double-boost effect a couple of times on MG101.

Suggested fix: only able to do sm_pause when velocity=0.

**Comment by MestroGroup** [comment]
I have added the above suggestion, requiring a velocity of 0 to use pause.
Also made some changes to the timer display to make it generally better for the user.
