### ISSUE TITLE
ranks arent displayed in brackets like on 1.7 [new], [new+] and no colours have been assigned like on 1.7

### ISSUE THREAD

**Issue by ItsNotSpaghetti** [MestroGroup/mgTimer-Public#36]

**Comment by Disillusioned1** [comment]
Can we have a rank revamp? New names / order? The ranks like Skilled and Skilled+ or Novice and Novice+, the + rank offers little incentive for that rank and makes it feel like you've not really improved. Only a suggestion, not a fix.

**Comment by MestroGroup** [comment]
Resolved 2507
