### ISSUE TITLE
!r requires to be typed twice or keybind pressed twice

### ISSUE THREAD

**Issue by cynlik** [MestroGroup/mgTimer-Public#38]
community suggestion: make it only 1 press or type required as in 1.7v

**Comment by qrvyboi** [comment]
edited community suggestion: make it an option to be able to press the bind twice or type !r twice for those who would prefer that in the !options menu

(if and where possible, and not a priority change).

**Comment by MestroGroup** [comment]
Working as intended for now on staged maps.
