### ISSUE TITLE
custom title doesnt work on /vip

### ISSUE THREAD

**Issue by ItsNotSpaghetti** [MestroGroup/mgTimer-Public#4]

**Comment by cynlik** [comment]
/title leads to /vip menu and neither work

**Comment by MestroGroup** [comment]
This is possibly working as intended, will review for overnight hotfix.

**Comment by MestroGroup** [comment]
Can I confirm in the next session that players have tried in game and console;

[CHAT] /customtitle OR !customtitle "test"
[CONSOLE] sm_customtitle "test"


ALSO

[CHAT] /toggletitle OR !toggletitle
[CONSOLE] sm_toggletitle

**Comment by MestroGroup** [comment]
![VIP Titles](https://user-images.githubusercontent.com/6832917/87861204-05c15b00-c93c-11ea-8346-48a4feba477a.png)

Works fine.
