### ISSUE TITLE
Half-sideways doesn't appear to be working correctly.

### ISSUE THREAD

**Issue by obsidian5m** [MestroGroup/mgTimer-Public#42]
I was testing the styles, I tried Normal, works fine. I switched to Sideways, locks your keys to W/S. I then switched to HSW and no combination of WASD keys allows me to stick to a ramp - even with the correct angle to the ramp.

Not sure if this is related to me trying this after Sideways, however. 

I can reproduce this on MG101.

**Comment by MestroGroup** [comment]
Hi Will
HSW should be functioning correctly, or similarly to how it is currently
functioning on MG1. MG101 is currently configured to Surf HSW.

**Comment by obsidian5m** [comment]
Hi Lee,
I've retested this today after thinking about some client-side factors (such as binds) that could be affecting this. I've removed all binds now.

As of today, I CAN surf HSW in Normal-mode, but cannot surf HSW in HSW-mode.
Could this be a case of plugins you've got loaded in on the side? Not sure what would cause this.

**Comment by obsidian5m** [comment]
Done a little bit more testing. It appears as if you've stopped W, A, S and D all from moving individually. 
Combinations of keys seem to work and I *think* I'm only able to stick (momentarily) to a ramp if I'm gaining speed whilst turning in HSW, which is unexpected.

Not an expert by any stretch of the imagination, but I think there's a coding error going on.

I'm assuming that you're checking for if I'm gaining momentum whilst moving with WA/WD, so when I use those keys into a ramp I'm gaining negative velocity (gaining speed in a direction I'm not facing) and this is interfering or not permitted in your code.

**Comment by MestroGroup** [comment]
Will compare to current operational timer and reproduce issues mentioned above.
Intended hotfix 2607

**Comment by obsidian5m** [comment]
HSW confirmed working fine (in both Normal and HSW styles) on MG1 as of 6:30 BST 2507.
Also works as expected on MG101.

Unsure if you've applied a hotfix but regardless seems to work fine now.
