### ISSUE TITLE
!nominate list in a random order

### ISSUE THREAD

**Issue by AlsterDev** [MestroGroup/mgTimer-Public#43]
Issue: when selecting "All maps" or "incomplete maps" in the !nominate menu, the subsequent list show maps with no apparent order.

Expectation: Maps should be displayed in alphabetical order, and the list should be updated whenever new maps are added (or at every restart or every week or whatever, as long as the list isn't a complete mess.

Also, sometimes **_!nominate <mapname>_** results in an error that the map can't be found, even if it can find the full map name (e.g if the map was _surf_123_abc_, and the user did **_!nominate surf_123_**, it sometimes results in the error "The map surf_123_abc could not be found"

**Comment by MestroGroup** [comment]
Updated Nominate Plugin to order maps correctly.
