### ISSUE TITLE
surf_kitsune2 momentum loss between stages

### ISSUE THREAD

**Issue by Cuntbucket** [MestroGroup/mgTimer-Public#46]
When going to the next stage on surf_kitsune2 you lose all your speed. This isn't the case on other maps that keep momentum inbetween stages (surf_ace, surf_kitsune) so I'm guessing this ones bugged.

**Comment by MestroGroup** [comment]
Resolved the above map, although the issue spans across many. Exploring a fix now.

**Comment by MestroGroup** [comment]
Resolved, thanks for your report.
Round change to take effect on all live games.
