### ISSUE TITLE
surf hsw bug

### ISSUE THREAD

**Issue by RIHO48** [MestroGroup/mgTimer-Public#5]
i think it is bhop hsw instead of surf HSW

**Comment by MestroGroup** [comment]
More information required, can't do anything with this.

**Comment by cynlik** [comment]
BHOP HSW = W/A or W/D 
SURF HSW = W/A and S/D or W/D and S/A

expected: 

surf server to allow only use of W/A and S/D or W/D and S/A
bhop server to allow only use of W/A or W/D

**Comment by MestroGroup** [comment]
Should be resolved.
Will keep open for testing, feedback required please.
