### ISSUE TITLE
Practice mode doesn't automatically reset.

### ISSUE THREAD

**Issue by Cuntbucket** [MestroGroup/mgTimer-Public#57]
Checkpoints work fine, but every time you 'die' you have to retype !prac to get to your checkpoint, it doesn't reset your position.

**Comment by cynlik** [comment]
not a bug. please remove. thank you

**Comment by WillSO93** [comment]
i'd recommend using the binds sm_cp and sm_tele when using practice mode.
i personally use mouse1 and mouse2.

bind mouse1 sm_cp; bind mouse2 sm_tele;
